<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Page</title>
</head>
<body>
  <header>
    <div>LOGO</div>
    <ul>
      <li>
        <a href="/">Accueil</a>
      </li>
      <li>
        <a href="/posts/index">Articles</a>
      </li>
    </ul>
  </header>
  
  <h1>Welcome <?= htmlspecialchars($name) ?>!</h1>
  <p>Bonjour depuis la vue !</p>

  <ul>
    <?php foreach ($couleurs as $couleur): ?>
      <li><?= htmlspecialchars($couleur) ?></li>
      <?php endforeach; ?>
  </ul>
</body>
</html>