<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>404 Not Found</title>
</head>

<body>
  <header>
    <div>LOGO</div>
    <ul>
      <li>
        <a href="/">Accueil</a>
      </li>
      <li>
        <a href="/posts/index">Articles</a>
      </li>
    </ul>
  </header>

  <h1>404 Page non trouvée!</h1>
  <p>La page que vous recherché n'a pas été trouvée.</p>

</body>

</html>