<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Posts Page</title>
</head>
<body>
  <header>
    <div>LOGO</div>
    <ul>
      <li>
        <a href="/">Accueil</a>
      </li>
      <li>
        <a href="/posts/index">Articles</a>
      </li>
    </ul>
  </header>
  
  <h1>Liste des articles</h1>
  <p>voici la liste des articles</p>

  <ul>
    <?php foreach ($posts as $post): ?>
      <h2><?= htmlspecialchars($post['title']) ?></h2>
      <p><?= $post['content'] ?></p>
      <?php endforeach; ?>
  </ul>
</body>
</html>